### ISSUE TITLE
Create Flight Pilots Div

### ISSUE THREAD

**Issue by jamalbrowning** [nss-evening-cohort-12/nutshell-alces#77]
# User Story
As a user, I should be able to choose Pilots for a flight.
# AC
**WHEN**  a User schedules a flight they should be able to choose the Pilots from 2 dropdowns
*THEN**  then that data should be pushed to flightCrew (#59 )

## Dev Notes
- [x] Create a `<div id="crew"></div>`  in the `<div id="flightDashboardContainer>` 
- [x] create pilots.js for adding pilots in the `flightDashboard` folder
- [x] create a function with bootstrap downs for pilots that prints `utils.printToDom('#crew', domString)`

- scss in conjunction with (#78)
```css
#crew {
  position: absolute;  
  bottom: 0;
  width: 100%;
  height: 50%;
}
```
